// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjgmufazhhdnsgsirnbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqZ211ZmF6aGhkbnNnc2lybmJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NDMyMDcsImV4cCI6MjA1NTExOTIwN30.7pWt-SPRQ2bAn5_EbWrJgKAxZ6jr4ESvmWlEykgdtbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);